# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_img=QtWidgets.QLabel(self.centralwidget)
        self.input_img.setGeometry(QtCore.QRect(28,85,500,500))
        self.input_img.setText('')
        self.input_img.setScaledContents(True)
        self.input_img.setAlignment(QtCore.Qt.AlignCenter)
        self.input_img.setObjectName('input_img')

        self.export_img=QtWidgets.QLabel(self.centralwidget)
        self.export_img.setGeometry(QtCore.QRect(674,85,500,500))
        self.export_img.setText('')
        self.export_img.setScaledContents(True)
        self.export_img.setAlignment(QtCore.Qt.AlignCenter)
        self.export_img.setObjectName('export_img')


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 161, 221))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 161, 221))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")


        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 160, 101, 94))
        self.pushButton.setStyleSheet("background-image:url(:/png/import.PNG)")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton_input")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(550, 350, 101, 31))
        font=QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.comboBox.addItem('')




        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(550, 220, 101, 94))
        self.textEdit.setStyleSheet("color:rgb(255, 0, 0)")
        self.textEdit.setObjectName("textEdit")


        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 160, 101, 101))
        self.pushButton_2.setStyleSheet("background-image:url(:/png/convert.PNG)")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_conversion")

        self.loding=QtWidgets.QLabel(self.centralwidget)
        self.loding.setGeometry(QtCore.QRect(550,250,100,100))
        self.loding.setText('')
        self.loding.setObjectName('loding')

        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.label.setText(_translate("MainWindow", "TextLabel"))
        # self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "请输入字符！"))
        self.comboBox.setItemText(0,_translate('MainWindow','清晰'))
        self.comboBox.setItemText(1, _translate('MainWindow', '一般'))
        self.comboBox.setItemText(2, _translate('MainWindow', '字符'))

import img_qc_rc
